//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 09:01:46 PM CEST 
//


package com.example.playlist.userinfo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.playlist.userinfo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.playlist.userinfo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserInfoRequest }
     * 
     */
    public UserInfoRequest createUserInfoRequest() {
        return new UserInfoRequest();
    }

    /**
     * Create an instance of {@link UserInfoResponse }
     * 
     */
    public UserInfoResponse createUserInfoResponse() {
        return new UserInfoResponse();
    }

}
